version: '3'
services:
  proxy:
    image: nginx:1.13.3-alpine
    container_name: proxy
    volumes:
      - ./proxy/certs:/etc/nginx/certs
      - ./proxy/sites:/etc/nginx/conf.d
      - ./proxy/htpasswd:/etc/nginx/users/auth
    ports:
      - 80:80
      - 443:443
      - 8080:8080 # REGISTRY
    links:
      - registry
      - hubstry

  registry:
    image: registry:2.6.2
    container_name: registry
    restart: always
    ports:
      - 5000:5000
    volumes:
      - registry:/var/lib/registry
      - ./registry/config.yml:/etc/docker/registry/config.yml

  hubstry:
    build: .
    container_name: hubstry
    ports:
      - 9090:9090
      - 8888:8888 # DEBUG
    volumes:
      - ./:/app
    links:
      - registry
    environment:
      - REGISTRY_URL=http://registry:5000
      - HUBSTRY_DEBUG=1 # REMOVE THIS FOR LIVE ENVIRONMENT

volumes:
  registry:
